"""Patch NB79 cells 4 (markdown header) + 4 (code) + 5 (code) to extract zips
into the LOCAL Colab filesystem (/content/) instead of Drive. Drive extraction
of tens of thousands of small files is unacceptably slow (each is a separate
Drive API call).
"""
import json
from pathlib import Path

p = Path(__file__).resolve().parent / 'stage2_notebook_79_P0_baseline.ipynb'
# adjust: this script lives at .../rmt_ppad_migration/notebooks/, so the
# notebook is right next to it.
if not p.exists():
    raise FileNotFoundError(p)
nb = json.loads(p.read_text(encoding='utf-8'))

# Cell 7 = markdown header for "Cell 4" of the user-facing flow.
nb['cells'][7]['source'] = (
    "### Cell 4: Extract RMT-PPAD's labels/masks into LOCAL Colab filesystem\n"
    "\n"
    "**Critical**: writing tens of thousands of small files into Drive is brutally slow\n"
    "(every file is a separate Drive API call). Both extractions go to `/content/` (the\n"
    "Colab instance's local SSD) which is ~20-50x faster.\n"
    "\n"
    "RMT-PPAD's `BDD_full.yaml` expects this layout at `BDD_LOCAL`:\n"
    "- `BDD_seg_mask/images/{train2017,val2017}/*.jpg`  - from your existing BDD image source\n"
    "- `BDD_seg_mask/labels/{train2017,val2017}/*.txt`  - from `BDD_detection_labels.zip`\n"
    "- `BDD_seg_mask/mask/lane/{train2017,val2017}/*.png`  - from `BDD_seg_masks.zip`\n"
    "- `BDD_seg_mask/mask/drivable/{train2017,val2017}/*.png`  - from `BDD_seg_masks.zip`\n"
    "\n"
    "Set `IMAGES_SOURCE` to point at your existing BDD raw images (directory or tarball).\n"
    "The cell tries (in order): symlink an existing dir; extract a tarball locally;\n"
    "raise a clear error. Idempotent: re-runs skip what already exists."
)

# Cell 8 = code for Cell 4: local extraction + image wiring + integrity check
nb['cells'][8]['source'] = (
    "import os, zipfile, subprocess, time\n"
    "from pathlib import Path\n"
    "\n"
    "DOWNLOADS_DIR = Path('/content/drive/MyDrive/EcoCAR/downloads/rmt_ppad_weights')\n"
    "IMAGES_SOURCE = '/content/drive/MyDrive/EcoCAR/datasets/bdd100k_clrkd_curve.tar'\n"
    "BDD_LOCAL = Path('/content/BDD_seg_mask')\n"
    "BDD_LOCAL.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "def _count(p, pattern, cap=5000):\n"
    "    n = 0\n"
    "    for _ in p.rglob(pattern):\n"
    "        n += 1\n"
    "        if n >= cap:\n"
    "            break\n"
    "    return n\n"
    "\n"
    "# Step 1: extract labels and masks zips into LOCAL /content/.\n"
    "for zip_name, marker_sub, file_ext in [\n"
    "    ('BDD_detection_labels.zip', 'labels', 'txt'),\n"
    "    ('BDD_seg_masks.zip',        'mask',   'png'),\n"
    "]:\n"
    "    zp = DOWNLOADS_DIR / zip_name\n"
    "    marker_dir = BDD_LOCAL / marker_sub\n"
    "    if not zp.exists():\n"
    "        print(f'[skip] {zip_name} not present in {DOWNLOADS_DIR}; re-run cell 3 first.')\n"
    "        continue\n"
    "    if marker_dir.exists() and _count(marker_dir, f'*.{file_ext}') >= 10:\n"
    "        print(f'[skip-extracted] {zip_name} -> {marker_dir} already populated')\n"
    "        continue\n"
    "    t0 = time.time()\n"
    "    print(f'[extract-local] {zp}  ->  {BDD_LOCAL}  (zip)')\n"
    "    with zipfile.ZipFile(zp) as zf:\n"
    "        zf.extractall(BDD_LOCAL)\n"
    "    print(f'  done in {time.time()-t0:.1f}s; {_count(marker_dir, f\"*.{file_ext}\")} {file_ext} files now present')\n"
    "\n"
    "# Step 2: BDD images. Detect existing or extract / symlink IMAGES_SOURCE.\n"
    "img_train = BDD_LOCAL / 'images' / 'train2017'\n"
    "img_val   = BDD_LOCAL / 'images' / 'val2017'\n"
    "\n"
    "if img_train.exists() and img_val.exists() and _count(img_train, '*.jpg') > 100:\n"
    "    print(f'[ok] images already at {img_train.parent} ({_count(img_train, \"*.jpg\")}+ train jpgs)')\n"
    "elif IMAGES_SOURCE is None:\n"
    "    print(f'[warn] IMAGES_SOURCE = None; populate {img_train} and {img_val} yourself before cell 5.')\n"
    "else:\n"
    "    src = Path(IMAGES_SOURCE)\n"
    "    if not src.exists():\n"
    "        raise FileNotFoundError(\n"
    "            f'IMAGES_SOURCE = {src} does not exist. Set it to your BDD image dir/tarball, '\n"
    "            'or download BDD100K from bdd-data.berkeley.edu.')\n"
    "\n"
    "    if src.is_file() and src.suffix in ('.tar', '.gz', '.tgz'):\n"
    "        scratch = Path('/content/bdd_images_scratch')\n"
    "        if scratch.exists() and _count(scratch, '*.jpg') > 100:\n"
    "            print(f'[skip-scratch] {scratch} already has images')\n"
    "        else:\n"
    "            scratch.mkdir(parents=True, exist_ok=True)\n"
    "            t0 = time.time()\n"
    "            print(f'[extract-local] {src}  ->  {scratch}  (tar)')\n"
    "            subprocess.check_call(['tar', '-xf', str(src), '-C', str(scratch)])\n"
    "            print(f'  done in {time.time()-t0:.1f}s')\n"
    "\n"
    "        def _find_split_dir(root, candidates):\n"
    "            for name in candidates:\n"
    "                for h in root.rglob(name):\n"
    "                    if h.is_dir() and _count(h, '*.jpg') > 0:\n"
    "                        return h\n"
    "            return None\n"
    "        train_src = _find_split_dir(scratch, ('train2017', 'train', 'training'))\n"
    "        val_src   = _find_split_dir(scratch, ('val2017', 'val', 'validation'))\n"
    "        if train_src is None or val_src is None:\n"
    "            print(f'[probe] auto-locate failed under {scratch}.')\n"
    "            print(f'        manually symlink:')\n"
    "            print(f'          ln -s <your_train_dir> {img_train}')\n"
    "            print(f'          ln -s <your_val_dir>   {img_val}')\n"
    "        else:\n"
    "            img_train.parent.mkdir(parents=True, exist_ok=True)\n"
    "            if not img_train.exists():\n"
    "                os.symlink(train_src, img_train)\n"
    "                print(f'[symlink] {img_train} -> {train_src}')\n"
    "            if not img_val.exists():\n"
    "                os.symlink(val_src, img_val)\n"
    "                print(f'[symlink] {img_val} -> {val_src}')\n"
    "\n"
    "    elif src.is_dir():\n"
    "        for sub_name, sub_dst in (('train2017', img_train), ('val2017', img_val)):\n"
    "            sub_src = src / sub_name\n"
    "            if not sub_src.exists():\n"
    "                for alt in ('train', 'training'):\n"
    "                    if (src / alt).exists():\n"
    "                        sub_src = src / alt\n"
    "                        break\n"
    "            if sub_src.exists():\n"
    "                sub_dst.parent.mkdir(parents=True, exist_ok=True)\n"
    "                if not sub_dst.exists():\n"
    "                    os.symlink(sub_src, sub_dst)\n"
    "                    print(f'[symlink] {sub_dst} -> {sub_src}')\n"
    "            else:\n"
    "                print(f'[miss] {sub_src} not found; cannot wire {sub_dst}')\n"
    "    else:\n"
    "        raise RuntimeError(f'Unsupported IMAGES_SOURCE type: {src}')\n"
    "\n"
    "# Final inspection of the local layout.\n"
    "print(f'\\n[final-inspect] {BDD_LOCAL}')\n"
    "EXPECTED = [\n"
    "    ('images/train2017',          'jpg', 100),\n"
    "    ('images/val2017',            'jpg',  10),\n"
    "    ('labels/train2017',          'txt', 100),\n"
    "    ('labels/val2017',            'txt',  10),\n"
    "    ('mask/lane/train2017',       'png', 100),\n"
    "    ('mask/lane/val2017',         'png',  10),\n"
    "    ('mask/drivable/train2017',   'png', 100),\n"
    "    ('mask/drivable/val2017',     'png',  10),\n"
    "]\n"
    "fail = 0\n"
    "for sub, ext, min_count in EXPECTED:\n"
    "    pp = BDD_LOCAL / sub\n"
    "    if not pp.exists():\n"
    "        print(f'  MISSING  {sub}')\n"
    "        fail += 1\n"
    "        continue\n"
    "    n = _count(pp, f'*.{ext}')\n"
    "    status = 'OK     ' if n >= min_count else 'PARTIAL'\n"
    "    print(f'  {status}  {sub:30s} ({n} {ext} files; need >={min_count})')\n"
    "    if status.strip() != 'OK':\n"
    "        fail += 1\n"
    "if fail:\n"
    "    print(f'\\n[warn] {fail} subdir(s) missing or partial. Cell 5 may fail.')\n"
    "else:\n"
    "    print(f'\\n[ok] BDD layout complete at {BDD_LOCAL}')"
)

# Cell 10 = code for Cell 5 (the runner invocation): point at local BDD root.
nb['cells'][10]['source'] = (
    "import os, sys\n"
    "from pathlib import Path\n"
    "\n"
    "# BDD_ROOT is LOCAL (populated in cell 4). Drive paths here would make every image\n"
    "# read a Drive API call -- killing val throughput.\n"
    "BDD_ROOT = '/content/BDD_seg_mask'\n"
    "RMT_PPAD_DST = '/content/drive/MyDrive/EcoCAR/yolop_vehicle_lane/stage2/rmt_ppad_migration/vendor/RMT-PPAD'\n"
    "CHECKPOINT = '/content/drive/MyDrive/EcoCAR/downloads/rmt_ppad_weights/rmt_ppad_best.pt'\n"
    "OUTPUT_JSON = '/content/drive/MyDrive/EcoCAR/yolop_vehicle_lane/stage2/rmt_ppad_migration/results/baseline_metrics.json'\n"
    "\n"
    "for path_, why in [\n"
    "    (BDD_ROOT,     'cell 4 must have populated this local dir'),\n"
    "    (RMT_PPAD_DST, 'cell 2 must have vendored the source'),\n"
    "    (CHECKPOINT,   'cell 3 must have downloaded the .pt'),\n"
    "]:\n"
    "    if not Path(path_).exists():\n"
    "        raise FileNotFoundError(f'prereq missing: {path_}  ({why})')\n"
    "\n"
    "cmd = [sys.executable, '-u',\n"
    "       'stage2/rmt_ppad_migration/P0_baseline/run_baseline_val.py',\n"
    "       '--rmt-ppad-root', RMT_PPAD_DST,\n"
    "       '--checkpoint', CHECKPOINT,\n"
    "       '--bdd-root', BDD_ROOT,\n"
    "       '--output-json', OUTPUT_JSON,\n"
    "       '--batch', '1',\n"
    "       '--imgsz', '640',\n"
    "       '--mask-thr', '0.45,0.9']\n"
    "log = os.path.join(LOG_DIR, 'NB79_baseline_val.log')\n"
    "run_streaming(cmd, log_path=log)"
)

# Convert source strings to list-of-lines (canonical .ipynb format) for changed cells.
for ci in (7, 8, 10):
    s = nb['cells'][ci]['source']
    if isinstance(s, str):
        parts = s.split('\n')
        nb['cells'][ci]['source'] = [p_ + '\n' for p_ in parts[:-1]] + ([parts[-1]] if parts[-1] else [])

# Clear outputs on the code cells we changed so the re-run is clean.
for ci in (8, 10):
    nb['cells'][ci]['outputs'] = []
    nb['cells'][ci]['execution_count'] = None

p.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('NB79 cells 4 + 5 updated; outputs cleared; BDD_ROOT is now /content/BDD_seg_mask (local).')
