"""Patch NB79 cell 4 (the BDD layout cell) to avoid the `str.replace('images', ...)`
bug in RMT-PPAD's dataset.py.

The bug: dataset.py line 187 does
    im_file.replace('images', 'mask/drivable')
which replaces ALL occurrences of 'images' in the path string. If the scratch
extraction dir is named `bdd_images_scratch`, the replace mangles BOTH the
scratch-dir name AND the per-image 'images/' segment, producing the broken
path `/content/bdd_mask/drivable_scratch/mask/drivable/val/X.png`.

Fix: rename the scratch dir to `bdd_extract_scratch` (no 'images' substring),
and copy the discovered jpgs into `/content/BDD_seg_mask/images/<split>/`
directly instead of symlinking. The copy is fast (it's all local SSD) and it
means `im_file` paths sit under BDD_seg_mask/images/<split>/ -- exactly one
'images' segment, which `replace` handles correctly.

If the user's existing scratch already exists with the old name, we simply
use the data that's there but re-route the symlinks to be hardlinks into
BDD_seg_mask/images/<split>/.
"""
import json
from pathlib import Path

p = Path(__file__).resolve().parent / 'stage2_notebook_79_P0_baseline.ipynb'
nb = json.loads(p.read_text(encoding='utf-8'))

# Cell 8 = code for "Cell 4" of the user-facing flow.
nb['cells'][8]['source'] = (
    "import os, zipfile, subprocess, time, shutil\n"
    "from pathlib import Path\n"
    "\n"
    "DOWNLOADS_DIR = Path('/content/drive/MyDrive/EcoCAR/downloads/rmt_ppad_weights')\n"
    "IMAGES_SOURCE = '/content/drive/MyDrive/EcoCAR/datasets/bdd100k_clrkd_curve.tar'\n"
    "BDD_LOCAL = Path('/content/BDD_seg_mask')\n"
    "BDD_LOCAL.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "# CRITICAL: scratch dir name MUST NOT contain the substring 'images'.\n"
    "# RMT-PPAD's dataset.py line 187 does `im_file.replace('images', task_name)`\n"
    "# which globally replaces every 'images' occurrence; if the image file\n"
    "# resolves through a path containing 'images' twice, the second one gets\n"
    "# mangled too. We use 'bdd_extract_scratch' (no 'images' substring).\n"
    "SCRATCH = Path('/content/bdd_extract_scratch')\n"
    "\n"
    "def _count(p, pattern, cap=5000):\n"
    "    n = 0\n"
    "    for _ in p.rglob(pattern):\n"
    "        n += 1\n"
    "        if n >= cap:\n"
    "            break\n"
    "    return n\n"
    "\n"
    "# Step 1: extract labels and masks zips into LOCAL /content/.\n"
    "for zip_name, marker_sub, file_ext in [\n"
    "    ('BDD_detection_labels.zip', 'labels', 'txt'),\n"
    "    ('BDD_seg_masks.zip',        'mask',   'png'),\n"
    "]:\n"
    "    zp = DOWNLOADS_DIR / zip_name\n"
    "    marker_dir = BDD_LOCAL / marker_sub\n"
    "    if not zp.exists():\n"
    "        print(f'[skip] {zip_name} not present in {DOWNLOADS_DIR}; re-run cell 3 first.')\n"
    "        continue\n"
    "    if marker_dir.exists() and _count(marker_dir, f'*.{file_ext}') >= 10:\n"
    "        print(f'[skip-extracted] {zip_name} -> {marker_dir} already populated')\n"
    "        continue\n"
    "    t0 = time.time()\n"
    "    print(f'[extract-local] {zp}  ->  {BDD_LOCAL}  (zip)')\n"
    "    with zipfile.ZipFile(zp) as zf:\n"
    "        zf.extractall(BDD_LOCAL)\n"
    "    print(f'  done in {time.time()-t0:.1f}s; {_count(marker_dir, f\"*.{file_ext}\")} {file_ext} files now present')\n"
    "\n"
    "# Step 2: BDD images. Detect existing or extract/relocate.\n"
    "img_train = BDD_LOCAL / 'images' / 'train2017'\n"
    "img_val   = BDD_LOCAL / 'images' / 'val2017'\n"
    "\n"
    "def _is_safe_jpg_dir(d):\n"
    "    'A jpg dir is safe iff its absolute path has exactly one `images` segment.'\n"
    "    if not d.exists():\n"
    "        return False\n"
    "    abs_path = str(d.resolve())\n"
    "    return abs_path.count('/images/') == 1 and _count(d, '*.jpg') > 0\n"
    "\n"
    "# If train/val images are already set up safely, do nothing.\n"
    "if _is_safe_jpg_dir(img_train) and _is_safe_jpg_dir(img_val):\n"
    "    print(f'[ok] images already at {img_train.parent} ({_count(img_train, \"*.jpg\")}+ train jpgs)')\n"
    "elif IMAGES_SOURCE is None:\n"
    "    print(f'[warn] IMAGES_SOURCE = None; populate {img_train} and {img_val} yourself before cell 5.')\n"
    "else:\n"
    "    src = Path(IMAGES_SOURCE)\n"
    "    if not src.exists():\n"
    "        raise FileNotFoundError(\n"
    "            f'IMAGES_SOURCE = {src} does not exist. Set it to your BDD image dir/tarball, '\n"
    "            'or download BDD100K from bdd-data.berkeley.edu.')\n"
    "\n"
    "    # Remove any stale symlinks from NB79 v1 (these pointed at\n"
    "    # /content/bdd_images_scratch which had the path-replace bug).\n"
    "    for stale in (img_train, img_val):\n"
    "        if stale.is_symlink():\n"
    "            print(f'[unlink] removing stale symlink {stale} -> {os.readlink(stale)}')\n"
    "            stale.unlink()\n"
    "\n"
    "    if src.is_file() and src.suffix in ('.tar', '.gz', '.tgz'):\n"
    "        if SCRATCH.exists() and _count(SCRATCH, '*.jpg') > 100:\n"
    "            print(f'[skip-scratch] {SCRATCH} already has images')\n"
    "        else:\n"
    "            SCRATCH.mkdir(parents=True, exist_ok=True)\n"
    "            t0 = time.time()\n"
    "            print(f'[extract-local] {src}  ->  {SCRATCH}  (tar)')\n"
    "            subprocess.check_call(['tar', '-xf', str(src), '-C', str(SCRATCH)])\n"
    "            print(f'  done in {time.time()-t0:.1f}s')\n"
    "\n"
    "        # Discover the actual jpg directories the tar created.\n"
    "        def _find_split_dir(root, candidates):\n"
    "            for name in candidates:\n"
    "                for h in root.rglob(name):\n"
    "                    if h.is_dir() and _count(h, '*.jpg') > 0:\n"
    "                        return h\n"
    "            return None\n"
    "        train_src = _find_split_dir(SCRATCH, ('train2017', 'train', 'training'))\n"
    "        val_src   = _find_split_dir(SCRATCH, ('val2017', 'val', 'validation'))\n"
    "        if train_src is None or val_src is None:\n"
    "            raise RuntimeError(\n"
    "                f'Could not auto-locate train/val image dirs under {SCRATCH}. '\n"
    "                f'List the structure and either rename or set IMAGES_SOURCE to '\n"
    "                f'a directory laid out as <root>/{{train2017,val2017}}/*.jpg.')\n"
    "\n"
    "        # HARDLINK the jpgs into BDD_LOCAL/images/<split>/. Hardlinks share\n"
    "        # the same inode so no disk doubled, and the path RMT-PPAD's dataset.py\n"
    "        # sees is `/content/BDD_seg_mask/images/<split>/X.jpg` -- exactly one\n"
    "        # 'images' segment, so .replace('images','mask/drivable') works.\n"
    "        for split_src, split_dst in ((train_src, img_train), (val_src, img_val)):\n"
    "            split_dst.parent.mkdir(parents=True, exist_ok=True)\n"
    "            split_dst.mkdir(parents=True, exist_ok=True)\n"
    "            existing = _count(split_dst, '*.jpg')\n"
    "            source_count = _count(split_src, '*.jpg')\n"
    "            if existing >= source_count * 0.95:\n"
    "                print(f'[skip-linked] {split_dst}: {existing} jpgs already present (>=95% of {source_count})')\n"
    "                continue\n"
    "            print(f'[hardlink] {split_src} -> {split_dst}  ({source_count} files)')\n"
    "            t0 = time.time()\n"
    "            for jpg in split_src.glob('*.jpg'):\n"
    "                target = split_dst / jpg.name\n"
    "                if target.exists():\n"
    "                    continue\n"
    "                try:\n"
    "                    os.link(jpg, target)  # hardlink: same inode, no double disk\n"
    "                except OSError:\n"
    "                    # cross-device or other FS quirk -> fall back to copy\n"
    "                    shutil.copy2(jpg, target)\n"
    "            print(f'  done in {time.time()-t0:.1f}s; now {_count(split_dst, \"*.jpg\")} jpgs at {split_dst}')\n"
    "\n"
    "    elif src.is_dir():\n"
    "        # User-supplied directory: copy/link directly to BDD_LOCAL.\n"
    "        for sub_name, sub_dst in (('train2017', img_train), ('val2017', img_val)):\n"
    "            sub_src = src / sub_name\n"
    "            if not sub_src.exists():\n"
    "                for alt in ('train', 'training'):\n"
    "                    if (src / alt).exists():\n"
    "                        sub_src = src / alt\n"
    "                        break\n"
    "            if not sub_src.exists():\n"
    "                print(f'[miss] {sub_src} not found; cannot wire {sub_dst}')\n"
    "                continue\n"
    "            sub_dst.parent.mkdir(parents=True, exist_ok=True)\n"
    "            sub_dst.mkdir(parents=True, exist_ok=True)\n"
    "            for jpg in sub_src.glob('*.jpg'):\n"
    "                target = sub_dst / jpg.name\n"
    "                if target.exists():\n"
    "                    continue\n"
    "                try:\n"
    "                    os.link(jpg, target)\n"
    "                except OSError:\n"
    "                    shutil.copy2(jpg, target)\n"
    "            print(f'[hardlink/copy] {sub_dst}: {_count(sub_dst, \"*.jpg\")} jpgs')\n"
    "    else:\n"
    "        raise RuntimeError(f'Unsupported IMAGES_SOURCE type: {src}')\n"
    "\n"
    "# Final inspection + safety check that no path contains a duplicate 'images'.\n"
    "print(f'\\n[final-inspect] {BDD_LOCAL}')\n"
    "EXPECTED = [\n"
    "    ('images/train2017',          'jpg', 100),\n"
    "    ('images/val2017',            'jpg',  10),\n"
    "    ('labels/train2017',          'txt', 100),\n"
    "    ('labels/val2017',            'txt',  10),\n"
    "    ('mask/lane/train2017',       'png', 100),\n"
    "    ('mask/lane/val2017',         'png',  10),\n"
    "    ('mask/drivable/train2017',   'png', 100),\n"
    "    ('mask/drivable/val2017',     'png',  10),\n"
    "]\n"
    "fail = 0\n"
    "for sub, ext, min_count in EXPECTED:\n"
    "    pp = BDD_LOCAL / sub\n"
    "    if not pp.exists():\n"
    "        print(f'  MISSING  {sub}')\n"
    "        fail += 1\n"
    "        continue\n"
    "    n = _count(pp, f'*.{ext}')\n"
    "    status = 'OK     ' if n >= min_count else 'PARTIAL'\n"
    "    print(f'  {status}  {sub:30s} ({n} {ext} files; need >={min_count})')\n"
    "    if status.strip() != 'OK':\n"
    "        fail += 1\n"
    "\n"
    "# Safety: confirm a sample image's RESOLVED absolute path contains 'images' exactly once.\n"
    "sample = next(img_val.glob('*.jpg'), None)\n"
    "if sample is not None:\n"
    "    resolved = str(sample.resolve())\n"
    "    n_images_segs = resolved.count('/images/')\n"
    "    if n_images_segs == 1:\n"
    "        print(f'\\n[path-safety] OK  sample {sample.name} resolves to {resolved}')\n"
    "        print(f'              `/images/` appears exactly once -> str.replace will be clean.')\n"
    "    else:\n"
    "        print(f'\\n[path-safety] FAIL sample resolves to {resolved}')\n"
    "        print(f'              `/images/` appears {n_images_segs} times -> RMT-PPAD will mangle paths.')\n"
    "        print(f'              Move or rename the scratch dir so it does not contain `images`.')\n"
    "        fail += 1\n"
    "\n"
    "if fail:\n"
    "    print(f'\\n[warn] {fail} check(s) failed. Cell 5 may fail.')\n"
    "else:\n"
    "    print(f'\\n[ok] BDD layout complete at {BDD_LOCAL}')"
)

# Convert to list-of-lines.
s = nb['cells'][8]['source']
if isinstance(s, str):
    parts = s.split('\n')
    nb['cells'][8]['source'] = [p_ + '\n' for p_ in parts[:-1]] + ([parts[-1]] if parts[-1] else [])

# Clear outputs on cells 4 + 5 so re-run is clean.
nb['cells'][8]['outputs'] = []
nb['cells'][8]['execution_count'] = None
nb['cells'][10]['outputs'] = []
nb['cells'][10]['execution_count'] = None

p.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('NB79 cell 4 updated: hardlinks instead of symlinks, scratch dir renamed, path-safety assertion added.')
