"""Generate NB77 - joint BDD training with CULane-KD teacher (from NB74)."""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
NOTEBOOKS = REPO / 'yolop_vehicle_lane' / 'stage2' / 'notebooks'
TEMPLATE = NOTEBOOKS / 'stage2_notebook_40_exp2kk_anchor_asl_amp_joint.ipynb'

nb = json.loads(TEMPLATE.read_text(encoding='utf-8'))
for c in nb['cells']:
    if c.get('cell_type') == 'code':
        c['outputs'] = []
        c['execution_count'] = None

nb['cells'][0]['source'] = (
    "# Stage 2 Notebook 77 - Joint BDD training with CULane-pretrained KD teacher (from NB74)\n"
    "\n"
    "**The real KD experiment.** NB72 self-distilled from NB62 (same architecture, similar quality) "
    "and got nothing useful -- garbage teacher in. NB77 uses a TRUE pretrained teacher: the lane head "
    "produced by NB74 (trained on CULane, the standard lane benchmark, with no BDD overlap).\n"
    "\n"
    "Two reasons this should help where NB72 didn't:\n"
    "1. The teacher saw a DIFFERENT data distribution (CULane = Chinese highways; BDD = US urban). "
    "Distillation transfers the teacher's curve-fitting prior, which has been refined on data "
    "the student has never seen.\n"
    "2. CULane pretrain has only lane supervision (no det conflict). The teacher's lane head is in "
    "a better local minimum than any joint-trained checkpoint we have.\n"
    "\n"
    "Note: NB76 separately downloads CLRKDNet's published GitHub checkpoint (DLA-34, 80.87 CULane F1) "
    "as a stronger alternative teacher. NB77 uses NB74's checkpoint because the head architecture "
    "matches our student exactly (CLRKDLaneHead -> CLRKDLaneHead). Using CLRKDNet's published "
    "weights would require an architecture adapter (DLA-34 backbone vs our RMT-GCA, slightly "
    "different head shape) -- doable as Exp2TTT but more engineering. NB77 is the immediate path.\n"
    "\n"
    "Speed flags applied (NB73 proved them stable):\n"
    "- `batch_size: 32`, `lr0: 4e-4` (sqrt-scaled from baseline 8 / 2e-4)\n"
    "- `workers: 6`, `prefetch_factor: 4`, `torch.compile(reduce-overhead)`\n"
    "- `backbone_lr_mult: 0.01` (joint-conflict throttle)\n"
    "- `cls_separate_path: true` (NB62 baseline)"
)

nb['cells'][1]['source'] = (
    "### Run mode\n"
    "1. Cell 2 mounts Drive and installs deps.\n"
    "2. Cell 3 extracts NB74's CULane-pretrain tar and locates the teacher checkpoint.\n"
    "3. Cell 4 trains the BDD joint model with KD enabled.\n"
    "\n"
    "Prerequisite: NB74 finished successfully and produced "
    "`/content/drive/MyDrive/EcoCAR/training_runs/exp69_rmt_gca_culane_lane_only_pretrain_culane8.tar`. "
    "If NB74 failed (as the first run did due to the CULane archive path issue), re-run NB74 first."
)

nb['cells'][3]['source'] = (
    "# Step 1: extract NB74's tar and find the teacher checkpoint.\n"
    "from pathlib import Path\n"
    "import os, sys, tarfile, shutil\n"
    "\n"
    "NB74_TAR = '/content/drive/MyDrive/EcoCAR/training_runs/exp69_rmt_gca_culane_lane_only_pretrain_culane8.tar'\n"
    "EXTRACT_DIR = '/content/exp69_rmt_gca_culane_lane_only_pretrain_culane8'\n"
    "\n"
    "if not Path(NB74_TAR).exists():\n"
    "    raise FileNotFoundError(\n"
    "        f'NB74 output {NB74_TAR} does not exist. Run NB74 first '\n"
    "        '(make sure cell 3 finds the CULane archives -- see NB74 cell 3 diagnostics).'\n"
    "    )\n"
    "\n"
    "if not Path(EXTRACT_DIR).exists() or not any(Path(EXTRACT_DIR).iterdir()):\n"
    "    print('Extracting', NB74_TAR, '->', EXTRACT_DIR)\n"
    "    Path(EXTRACT_DIR).mkdir(parents=True, exist_ok=True)\n"
    "    with tarfile.open(NB74_TAR, 'r') as tar:\n"
    "        tar.extractall(EXTRACT_DIR)\n"
    "else:\n"
    "    print('Already extracted')\n"
    "\n"
    "# Find the teacher .pt file -- look for best.pt or last.pt in the extracted tree.\n"
    "candidates = list(Path(EXTRACT_DIR).rglob('best.pt')) + list(Path(EXTRACT_DIR).rglob('last.pt'))\n"
    "if not candidates:\n"
    "    raise FileNotFoundError(\n"
    "        f'No best.pt or last.pt under {EXTRACT_DIR}. NB74 may have crashed before saving.'\n"
    "    )\n"
    "TEACHER_PT = str(candidates[0])\n"
    "print('Teacher checkpoint:', TEACHER_PT)\n"
    "print('Size:', Path(TEACHER_PT).stat().st_size / 1e6, 'MB')\n"
    "\n"
    "# Show what's inside the checkpoint -- helps debug architecture mismatch later.\n"
    "import torch\n"
    "ck = torch.load(TEACHER_PT, map_location='cpu', weights_only=False)\n"
    "state = ck.get('state_dict', ck.get('model', ck))\n"
    "if hasattr(state, 'state_dict'):\n"
    "    state = state.state_dict()\n"
    "if isinstance(state, dict):\n"
    "    lane_keys = [k for k in state.keys() if 'lane_head' in k][:5]\n"
    "    print(f'top-level keys: {len(state)}; lane_head sample: {lane_keys}')"
)

nb['cells'][4]['source'] = (
    "# Step 2: train BDD joint model with NB74 teacher distillation enabled.\n"
    "from pathlib import Path\n"
    "import os, sys\n"
    "\n"
    "CONFIG = 'stage2/configs/exp70_rmt_gca_anchor_cls_sep_vfl_culane_kd_full_data_joint.yaml'\n"
    "CURVE_TAR = '/content/drive/MyDrive/EcoCAR/datasets/bdd100k_clrkd_curve.tar'\n"
    "CURVE_ROOT = '/content/bdd100k_clrkd_curve'\n"
    "\n"
    "DEBUG_MODE = False\n"
    "\n"
    "if DEBUG_MODE:\n"
    "    RUN_TAG = 'debug'\n"
    "    EPOCHS = 2\n"
    "    BATCH_SIZE = 4\n"
    "    LIMIT_TRAIN = 512\n"
    "    LIMIT_VAL = 256\n"
    "    PRINT_EVERY = 5\n"
    "else:\n"
    "    RUN_TAG = 'full12'\n"
    "    EPOCHS = 12\n"
    "    BATCH_SIZE = 32\n"
    "    LIMIT_TRAIN = None\n"
    "    LIMIT_VAL = 1000\n"
    "    PRINT_EVERY = 50\n"
    "\n"
    "run_stem = Path(CONFIG).stem + '_' + RUN_TAG\n"
    "WORK_DIR = f'/content/{run_stem}'\n"
    "OUTPUT_TAR = f'/content/drive/MyDrive/EcoCAR/training_runs/{run_stem}.tar'\n"
    "LOG_FILE = os.path.join(LOG_DIR, f'{run_stem}_train.log')\n"
    "\n"
    "# Patch the config so teacher.lane_head_checkpoint points at the path we\n"
    "# discovered in cell 3. We write a patched yaml to /content so the\n"
    "# original config in the repo stays untouched.\n"
    "import yaml\n"
    "with open(CONFIG, 'r', encoding='utf-8') as f:\n"
    "    cfg = yaml.safe_load(f)\n"
    "cfg.setdefault('teacher', {})['lane_head_checkpoint'] = TEACHER_PT\n"
    "PATCHED_CONFIG = f'/content/{Path(CONFIG).stem}_patched.yaml'\n"
    "with open(PATCHED_CONFIG, 'w', encoding='utf-8') as f:\n"
    "    yaml.safe_dump(cfg, f)\n"
    "print('Patched config wrote teacher.lane_head_checkpoint =', TEACHER_PT)\n"
    "\n"
    "cmd = [\n"
    "    sys.executable, '-u', 'stage2/scripts/train_joint_model_experiment.py',\n"
    "    '--config', PATCHED_CONFIG,\n"
    "    '--curve-tar', CURVE_TAR,\n"
    "    '--curve-root', CURVE_ROOT,\n"
    "    '--work-dir', WORK_DIR,\n"
    "    '--output-tar', OUTPUT_TAR,\n"
    "    '--epochs', str(EPOCHS),\n"
    "    '--batch-size', str(BATCH_SIZE),\n"
    "    '--limit-val', str(LIMIT_VAL),\n"
    "    '--force-extract',\n"
    "    '--print-every', str(PRINT_EVERY),\n"
    "    '--workers', '6',\n"
    "    '--prefetch-factor', '4',\n"
    "    '--torch-compile',\n"
    "]\n"
    "if LIMIT_TRAIN is not None:\n"
    "    cmd.extend(['--limit-train', str(LIMIT_TRAIN)])\n"
    "\n"
    "print('DEBUG_MODE:', DEBUG_MODE, flush=True)\n"
    "print('Teacher:', TEACHER_PT, flush=True)\n"
    "print('About to run:', ' '.join(cmd), flush=True)\n"
    "print('Output tar:', OUTPUT_TAR, flush=True)\n"
    "print('Visible log file:', LOG_FILE, flush=True)\n"
    "run_streaming(cmd, log_path=LOG_FILE)"
)

nb['cells'][5]['source'] = (
    "## What to watch in NB77\n"
    "\n"
    "Reference NB73 (no KD, same speed flags, 12 ep full): matched_iou=0.558, oracle_f1=0.484, "
    "decoded_f1=0.050, val_lane_best_f1=0.110, gap=0.029.\n"
    "Reference NB72 (NB62-self-distill): matched_iou=0.549, decoded_f1=0.048 -- KD with bad teacher = no change.\n"
    "\n"
    "Pass criteria at epoch 12:\n"
    "- **`val/lane/distill` decreases monotonically** -- teacher signal is active and useful.\n"
    "- `val/matched_line_iou >= 0.56` -- preserve or beat NB73's geometry.\n"
    "- **`val/lane_best_f1 >= 0.15`** -- 1.5x NB73; CULane-pretrained teacher's cls knowledge transfers.\n"
    "- **`val/lane/decoded_f1 >= 0.07`** -- 1.5x NB73; the smoking gun for KD actually working.\n"
    "- `pos_score - neg_score >= 0.04` -- KD helps cls separation past the anchor-head ceiling.\n"
    "\n"
    "Failure signals:\n"
    "- distill loss flat or rising: teacher checkpoint corrupted or arch mismatch silently failing.\n"
    "Verify cell 3's print of lane_head keys.\n"
    "- decoded_f1 unchanged from NB73: teacher trained on CULane doesn't transfer to BDD.\n"
    "Confirms NB72-style 'self-distill is useless' conclusion -- KD needs domain overlap.\n"
    "Next move would be NB76's CLRKDNet weights with a proper architecture adapter (Exp2TTT)."
)

out = NOTEBOOKS / 'stage2_notebook_77_culane_kd_anchor_cls_sep_vfl_joint.ipynb'
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('wrote', out)
